version: '3'
services:
  mysql:
    image: mysql
    volumes:
      - ./docker/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
